stages:
  process_data:
    cmd: python -m src.data.data_main
    deps:
    - data/raw/dataset.csv
    - src/data/data_main.py
    - src/visualization/data_visualization.py
    outs:
    - data/processed/processed_dataset.csv
    - reports/figures/
